use_frameworks!

platform :ios, '10.0'

target 'Swin_Example' do
  pod 'Swin', :path => '../', :testspecs => ['Tests']

  target 'Swin_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 8.0.7'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 8.0.0'
  end
end
